providers = ["..."]

[phases.setup]
nixPkgs = ["python313", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python bot.py"
